import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Image from "next/image";
import { Box, Button, Stack, Typography } from "@mui/material";

interface LoginProps {
    setUserLogged: React.Dispatch<React.SetStateAction<boolean>>;
}

const Login = ({ setUserLogged }: LoginProps) => {
    const { data: session, status } = useSession();
    const router = useRouter();

    useEffect(() => {
        if (session) {
            setUserLogged(true);
        }
    }, [router, session, setUserLogged]);

    if (status === "loading") {
        return null;
    }

    return (
        <>
            <Head>
                <title>DND Web App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Stack
                sx={{
                    background: "#1e293b",
                    height: "100%",
                    alignContent: "center",
                    alignItems: "center",
                    display: "flex",
                    px: 5,
                }}
            >
                <Box sx={{ mt: 10 }}>
                    <Image
                        src="/logoText.png"
                        alt="me"
                        width="600"
                        height="600"
                    />
                </Box>
                <Stack
                    sx={{
                        background: "#334155",
                        color: "white",
                        p: 5,
                        borderRadius: 5,
                        alignItems: "center",
                    }}
                >
                    <Typography sx={{ pb: 3, pt: 2 }}>
                        Please log into the site using your GitHub Account or
                        your Google Account.
                    </Typography>
                    <Button
                        variant="contained"
                        onClick={() => signIn()}
                        sx={{ bg: "#6b7280", width: 200 }}
                    >
                        Sign in
                    </Button>
                </Stack>
            </Stack>
        </>
    );
};

export default Login;
